### ISSUE TITLE
Noise node has banding artifacts

### ISSUE THREAD

**Issue by zauberparacelsus** [RodZill4/material-maker#250]
**Material Maker version:**  0.94a1

**OS/device including version:**
* 64bit Manjaro Linux, kernel 5.7.19
* nVidia GTX 1650 Super graphics card, driver 455.45.01

**Issue description:**
The noise node appears to have some directional banding artifacts, which are more apparent at higher grid sizes.  The issue is most apparent when a grid size of 2048px is used with a material size of 1024px

**Steps to reproduce:**
The following node setup displays the issue at its worst:
![image](https://user-images.githubusercontent.com/548168/103015322-353d4a80-450e-11eb-9730-6dedfb4b50d1.png)

**Comment by some9000** [comment]
Can confirm, I also noticed this recently. You can easily see repeating diagonal lines, no matter what the random seed is:

![VfQa7MLUKu](https://user-images.githubusercontent.com/17021558/105890355-ebb5b300-6017-11eb-90ac-1f88d8c04b8f.gif)

**Comment by some9000** [comment]
I don't know how efficient it is, but perhaps this could be used?

https://thebookofshaders.com/10/

**Comment by Tar0x** [comment]
@RodZill4 This was fixed, so it should be closed.

**Comment by williamchange** [comment]
This still happens (`1.4b2`)

<img width="752" alt="Image" src="https://github.com/user-attachments/assets/905eda15-c080-4c5a-a249-4b18c3da9b2f" />

a better hashing function (that does not rely on trig functions - as that can vary between hardware) could probably be used - e.g. [Hash without Sine(MIT License)
](https://www.shadertoy.com/view/4djSRW)

**Comment by williamchange** [comment]
A potential fix could be removing `/$size` like this in main code:

```glsl
vec2 $(name_uv)_uv = floor($uv*$size);
```

before / after:

https://github.com/user-attachments/assets/db06ffc0-40f3-4c76-a233-626605032dcd
